name: daily-cron-job
on: push
jobs:
  cron:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: send
        run: |
          curl --request POST \
          --url ${{ secrets.ENDPOINT }} \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
