name: daily-cron-job
on:
  schedule:
    - cron: "0 8 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    environment: Production
    steps:
      - name: daily-cron-job
        env:
          ENDPOINT: ${{ secrets.ENDPOINT }}
          ACTION_KEY: ${{ secrets.ACTION_KEY }}
        run: |
          curl --request POST \
          --url '$ENDPOINT' \
          --header 'Authorization: Bearer $ACTION_KEY'
