name: daily-cron-job
on:
  schedule:
    # every day at 8 AM CST
    - cron: "0 13 * * *"
jobs:
  cron:
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: send
        run: |
          curl --request POST \
          --url ${{ secrets.ENDPOINT }} \
          --header 'Authorization: Bearer ${{ secrets.ACTION_KEY }}'
